/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void btnSeeStage1_click(GButton source, GEvent event) { //_CODE_:btnSeeStage1:922994:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
  stageWindow1.setVisible(true);
} //_CODE_:btnSeeStage1:922994:

synchronized public void stageWindow1_draw(PApplet appc, GWinData data) { //_CODE_:stageWindow1:419724:
  appc.background(230);
} //_CODE_:stageWindow1:419724:

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:txtAirResistanceStage1:224235:
  println("textfield1 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:txtAirResistanceStage1:224235:

public void textfield1_change2(GTextField source, GEvent event) { //_CODE_:txtParatrooperWeightStage1:677814:
  println("textfield1 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:txtParatrooperWeightStage1:677814:

public void btnCalculateStage1_click(GButton source, GEvent event) { //_CODE_:btnCalculateStage1:648969:
  println("btnCalculateStage1 - GButton >> GEvent." + event + " @ " + millis());
  float airResistance = float(txtAirResistanceStage1.getText());
  float paratrooperMass = float(txtParatrooperWeightStage1.getText());
  float gravity = 9.81;
  weigth = paratrooperMass * gravity;
  netForce = airResistance - weigth;
  paratrooperAcceleration = netForce / paratrooperMass;
  lblFormulaPart1Stage1.setText("W = mg => " + paratrooperMass + " * 9.81 m/s2 = " + nf(weigth, 0, 2) + " N");
  lblFormulaPart2Stage1.setText("ΣF_y = F_aire - W => " + airResistance + " - " + nf(weigth, 0, 2) + " = " + nf(netForce, 0, 2) + " N");
  lblFormulaPart3Stage1.setText("a_y = ΣF_y / m => " + nf(netForce, 0, 2) + "N" + " / " + paratrooperMass + " = " + nf(paratrooperAcceleration, 0, 2) + " m/s2");
  lblNetForceStage1.setText("Fuerza neta que actúa sobre ella: " + nf(netForce, 0, 2) + " N");
  lblParatrooperAcceleration.setText("Aceleración del paracaidista: " + nf(paratrooperAcceleration, 0, 2) + " m/s2");
} //_CODE_:btnCalculateStage1:648969:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  btnSeeStage1 = new GButton(this, 131, 64, 200, 30);
  btnSeeStage1.setText("Ver escenario 1");
  btnSeeStage1.addEventHandler(this, "btnSeeStage1_click");
  stageWindow1 = GWindow.getWindow(this, "Escenario 1", 0, 0, 1150, 500, JAVA2D);
  stageWindow1.noLoop();
  stageWindow1.setActionOnClose(G4P.CLOSE_WINDOW);
  stageWindow1.addDrawHandler(this, "stageWindow1_draw");
  lblTitleStage1 = new GLabel(stageWindow1, 0, 44, 1150, 20);
  lblTitleStage1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lblTitleStage1.setText("Escenario 1");
  lblTitleStage1.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  lblTitleStage1.setOpaque(false);
  lblStatementStage1 = new GLabel(stageWindow1, 0, 71, 1150, 20);
  lblStatementStage1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lblStatementStage1.setText("Caída libre desde un avión en paracaídas, en donde se tomará en cuenta la resistencia del aire. (Tierra: 9,81 m/s²)");
  lblStatementStage1.setOpaque(false);
  lblAirResistanceStage1 = new GLabel(stageWindow1, 90, 178, 394, 20);
  lblAirResistanceStage1.setText("Resistencia del aire");
  lblAirResistanceStage1.setOpaque(false);
  txtAirResistanceStage1 = new GTextField(stageWindow1, 90, 214, 394, 30, G4P.SCROLLBARS_NONE);
  txtAirResistanceStage1.setPromptText("Ingrese la resistencia del aire");
  txtAirResistanceStage1.setOpaque(true);
  txtAirResistanceStage1.addEventHandler(this, "textfield1_change1");
  txtParatrooperWeightStage1 = new GTextField(stageWindow1, 624, 214, 394, 30, G4P.SCROLLBARS_NONE);
  txtParatrooperWeightStage1.setPromptText("Ingrese el peso del paracaidista");
  txtParatrooperWeightStage1.setOpaque(true);
  txtParatrooperWeightStage1.addEventHandler(this, "textfield1_change2");
  lblParatrooperWeightStage1 = new GLabel(stageWindow1, 624, 178, 394, 20);
  lblParatrooperWeightStage1.setText("Peso del paracaidista");
  lblParatrooperWeightStage1.setOpaque(false);
  lblNetForceStage1 = new GLabel(stageWindow1, 89, 273, 394, 20);
  lblNetForceStage1.setText("Fuerza neta que actúa sobre ella: 0 N");
  lblNetForceStage1.setOpaque(false);
  lblParatrooperAcceleration = new GLabel(stageWindow1, 625, 272, 393, 20);
  lblParatrooperAcceleration.setText("Aceleración del paracaidista:0.00 m/s2");
  lblParatrooperAcceleration.setOpaque(false);
  lblFormulaStage1 = new GLabel(stageWindow1, -2, 382, 1150, 20);
  lblFormulaStage1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lblFormulaStage1.setText("Formulas");
  lblFormulaStage1.setOpaque(false);
  btnCalculateStage1 = new GButton(stageWindow1, 390, 318, 367, 44);
  btnCalculateStage1.setText("Calcular");
  btnCalculateStage1.addEventHandler(this, "btnCalculateStage1_click");
  lblFormulaPart1Stage1 = new GLabel(stageWindow1, 286, 414, 762, 20);
  lblFormulaPart1Stage1.setTextAlign(GAlign.LEFT, GAlign.LEFT);
  lblFormulaPart1Stage1.setText("Formula Parte 1");
  lblFormulaPart1Stage1.setOpaque(false);
  lblFormulaPart2Stage1 = new GLabel(stageWindow1, 285, 442, 762, 20);
  lblFormulaPart2Stage1.setText("Formula parte 2");
  lblFormulaPart2Stage1.setOpaque(false);
  lblFormulaPart3Stage1 = new GLabel(stageWindow1, 285, 469, 761, 20);
  lblFormulaPart3Stage1.setText("Formula Parte 3");
  lblFormulaPart3Stage1.setOpaque(false);
  stageWindow1.loop();
}

// Variable declarations 
// autogenerated do not edit
GButton btnSeeStage1; 
GWindow stageWindow1;
GLabel lblTitleStage1; 
GLabel lblStatementStage1; 
GLabel lblAirResistanceStage1; 
GTextField txtAirResistanceStage1; 
GTextField txtParatrooperWeightStage1; 
GLabel lblParatrooperWeightStage1; 
GLabel lblNetForceStage1; 
GLabel lblParatrooperAcceleration; 
GLabel lblFormulaStage1; 
GButton btnCalculateStage1; 
GLabel lblFormulaPart1Stage1; 
GLabel lblFormulaPart2Stage1; 
GLabel lblFormulaPart3Stage1; 
